SELECT *
FROM STUDENT;



--APPLY CASE ON STUDENT TABLE.
--MARKS <50 THEN 'PASSEDCLASS'
--MARKS BETWEEN 45 TO 65 THEN 'AVEGR'
--MARKS >65 THEN 'TOPPER'


SELECT SNAME,GENDER,MARKS,
 CASE
WHEN MARKS<=45 THEN 'FAILED'
WHEN MARKS BETWEEN 46 AND 65 THEN 'AVERAGE'
WHEN MARKS BETWEEN 66 AND 85 THEN 'DISTINCTION'
ELSE 'TOPPER' END AS MARKS_GRADE
FROM STUDENT;


SELECT SNAME,GENDER,MARKS,
 CASE
WHEN MARKS<=45 THEN 'FAILED'
WHEN MARKS BETWEEN 46 AND 65 THEN 'AVERAGE'
WHEN MARKS IS NULL THEN 'INSUFFIENT'
ELSE 'TOPPERS'
 END AS MARKS_GRADE
FROM STUDENT;

