SELECT *
FROM EMPLOYEES;

SELECT FNAME,SALARY,
 CASE
WHEN SALARY BETWEEN  350 AND 450 THEN 'D'
WHEN SALARY BETWEEN 451 AND 550 THEN 'C'
WHEN SALARY BETWEEN 551 AND 655 THEN 'B'
WHEN SALARY BETWEEN 656 AND 855 THEN 'A'
ELSE 'A+' END AS SALARY_GRADE
FROM EMPLOYEES;