SELECT *
FROM EMPLOYEES;

--WAQ-TO DISPLAY THOSE EMPLOYEES WHOSE SALARY > AVG SALARY 
SELECT FNAME, SALARY,DID
FROM   EMPLOYEES OUTER
WHERE  SALARY > ( SELECT AVG(salary)
          FROM   employees
          WHERE  DID = OUTER.DID );
          
--1	ANIL	800	20
SELECT FNAME, SALARY,DID
FROM   EMPLOYEES OUTER
WHERE  800 > ( 750);
          
