--RECORDS INSERTING IN STUDENT TABLE
INSERT INTO STUDENT VALUES(1,'Anil','M'	,65);
INSERT INTO STUDENT VALUES(2,'Tanvir','M'	,45);
INSERT INTO STUDENT VALUES(3,'Rakesh','M'	,95);
INSERT INTO STUDENT VALUES(4,'Shubham','M'	,85);
INSERT INTO STUDENT VALUES(1,'Anil','M'	,65);
INSERT INTO STUDENT VALUES(2,'Tanvir','M'	,45);
INSERT INTO STUDENT VALUES(1,'Anil','M'	,65);
INSERT INTO STUDENT VALUES (1,'Anil','M',NULL);
INSERT INTO STUDENT VALUES (2,'Tanvir','M'	,NULL);

commit;

